from __future__ import annotations

# 中文注释：reconcile 状态码单点定义，避免代码与 schema 漂移。
RECONCILE_STATUS_SUBMITTED = "submitted"
RECONCILE_STATUS_FILLED = "filled"
RECONCILE_STATUS_CANCELED = "canceled"
RECONCILE_STATUS_REJECTED = "rejected"
RECONCILE_STATUS_FAILED = "failed"

RECONCILE_STATUSES = (
    RECONCILE_STATUS_SUBMITTED,
    RECONCILE_STATUS_FILLED,
    RECONCILE_STATUS_CANCELED,
    RECONCILE_STATUS_REJECTED,
    RECONCILE_STATUS_FAILED,
)
