from __future__ import annotations

# 中文注释：risk_state 迁移原因码单点定义，避免规则实现与 schema 枚举漂移。
RISK_STATE_CHANGE_REASON_REJECT_FROZEN = "reject_frozen"
RISK_STATE_CHANGE_REASON_REJECT_REDUCE_ONLY = "reject_reduce_only"
RISK_STATE_CHANGE_REASON_PRESSURE_WARN = "pressure_warn"
RISK_STATE_CHANGE_REASON_HYSTERESIS_SOFTEN = "hysteresis_soften"
RISK_STATE_CHANGE_REASON_DEFAULT_NORMAL = "default_normal"

RISK_STATE_CHANGE_REASONS = (
    RISK_STATE_CHANGE_REASON_REJECT_FROZEN,
    RISK_STATE_CHANGE_REASON_REJECT_REDUCE_ONLY,
    RISK_STATE_CHANGE_REASON_PRESSURE_WARN,
    RISK_STATE_CHANGE_REASON_HYSTERESIS_SOFTEN,
    RISK_STATE_CHANGE_REASON_DEFAULT_NORMAL,
)

RISK_STATE_CHANGE_REASON_ZH = {
    RISK_STATE_CHANGE_REASON_REJECT_FROZEN: "命中冻结类风控拒绝，风险状态提升为 frozen",
    RISK_STATE_CHANGE_REASON_REJECT_REDUCE_ONLY: "命中降风险类风控拒绝，风险状态提升为 reduce_only",
    RISK_STATE_CHANGE_REASON_PRESSURE_WARN: "规则压力接近阈值，风险状态提升为 warn",
    RISK_STATE_CHANGE_REASON_HYSTERESIS_SOFTEN: "触发状态降级防抖，风险状态先过渡到 warn",
    RISK_STATE_CHANGE_REASON_DEFAULT_NORMAL: "未命中高风险条件，风险状态保持 normal",
}

