from __future__ import annotations

# strategy_gate 原因码单点来源，避免同义词漂移。
STRATEGY_GATE_REASON_SIGNAL_REJECTED = "signal_rejected"
STRATEGY_GATE_REASON_SIGNAL_STALE = "signal_stale"
STRATEGY_GATE_REASON_FRAGILITY_HIGH_BLOCK_INCREASE = "fragility_high_block_increase"
STRATEGY_GATE_REASON_DIRECTION_BIAS_MISMATCH = "direction_bias_mismatch"
STRATEGY_GATE_REASON_LIQUIDITY_VACUUM = "liquidity_vacuum"
STRATEGY_GATE_REASON_HORIZON_CONFLICT = "horizon_conflict"
STRATEGY_GATE_REASON_TRANSITION_AND_UNCERTAIN = "transition_and_uncertain"

STRATEGY_GATE_REASON_CODES = (
    STRATEGY_GATE_REASON_SIGNAL_REJECTED,
    STRATEGY_GATE_REASON_SIGNAL_STALE,
    STRATEGY_GATE_REASON_FRAGILITY_HIGH_BLOCK_INCREASE,
    STRATEGY_GATE_REASON_DIRECTION_BIAS_MISMATCH,
    STRATEGY_GATE_REASON_LIQUIDITY_VACUUM,
    STRATEGY_GATE_REASON_HORIZON_CONFLICT,
    STRATEGY_GATE_REASON_TRANSITION_AND_UNCERTAIN,
)

